// src/services/ai.js — draft & hook generation.
// If ANTHROPIC_API_KEY is set, drafts are generated by Claude; otherwise
// deterministic style templates keep the app fully working without a key.

const API_KEY = process.env.ANTHROPIC_API_KEY;
const MODEL = process.env.ANTHROPIC_MODEL || 'claude-sonnet-4-20250514';

const STYLE_GUIDES = {
  bold: 'Confident, punchy, contrarian-but-substantive. Short paragraphs. Strong opening claim.',
  minimal: 'Quiet, lowercase, spare. One clear idea. No hype, no emoji, generous line breaks.',
  electric: 'High-energy, builder-culture voice. Momentum and verbs. One emoji max.',
};

const TEMPLATES = {
  bold: (n, t) =>
    `Hot take on ${t}: nobody remembers "the team." They remember ${n}.\n\nYour name is the asset. ${cap(t)} is just the proof of work behind it.\n\nBuild the name first. The rest compounds.`,
  minimal: (n, t) =>
    `a quiet note on ${t}.\n\n${n} doesn't post to fill a feed — every piece earns its place.\n\none clear idea about ${t} beats ten loud ones.`,
  electric: (n, t) =>
    `NEW DROP from ${n} ⚡ — ${t}.\n\nThis isn't a side quest. ${cap(t)} is the rep, and every rep compounds.\n\nShip today. Sign your name to it.`,
};

const cap = (s) => s.charAt(0).toUpperCase() + s.slice(1);

/* Every name deterministically maps to its own accent color — part of "the model". */
const ACCENTS = ['#2B3CFF','#6B2BFF','#0E7AFF','#00A872','#FF5C38','#E62E6B','#D97706','#8B5CF6'];
export function nameAccent(name) {
  let h = 0;
  for (const ch of String(name).toLowerCase()) h = (h * 31 + ch.charCodeAt(0)) >>> 0;
  return ACCENTS[h % ACCENTS.length];
}

function fallbackModel(name, niche) {
  const first = name.split(' ')[0];
  return {
    color: nameAccent(name),
    style: ['bold', 'electric', 'minimal'][name.length % 3],
    tagline: `There's only one ${first} in ${niche.toLowerCase()}.`,
    bio_linkedin: `${name} — ${niche}. I turn ideas into work people remember. Building in public, one post at a time.`,
    bio_x: `${niche.toLowerCase()} · thoughts by ${first} · there's only one brand of me`,
    hooks: [
      `Everyone is wrong about ${niche.toLowerCase()}. Here's what ${first} sees instead:`,
      `I spent 3 years on ${niche.toLowerCase()} so you can learn it in 3 minutes.`,
      `The ${niche.toLowerCase()} advice nobody gives you (because it's unglamorous):`,
      `Stop scrolling if ${niche.toLowerCase()} is on your roadmap this year.`,
      `${cap(niche.toLowerCase())}, explained the way I wish someone had explained it to me:`,
    ],
  };
}

/** Build the brand model for a profile — called at signup and when adding Pro profiles.
 *  With ANTHROPIC_API_KEY set, the model is genuinely AI-generated per name + niche;
 *  otherwise a deterministic model keeps everything working. The unique color is
 *  always derived from the name itself. */
export async function buildBrandModel({ name, niche }) {
  const base = fallbackModel(name, niche);
  if (!API_KEY) return base;
  try {
    const text = await callClaude(
      `Build a personal-brand model for "${name}", niche: "${niche}".\n` +
      `Respond with ONLY this JSON, no markdown fences, no commentary:\n` +
      `{"tagline":"<60 chars, punchy, no quotes inside>",` +
      `"bio_linkedin":"<max 200 chars, first person, confident>",` +
      `"bio_x":"<max 110 chars, lowercase ok, no hashtags>",` +
      `"hooks":["5 scroll-stopping first lines about ${niche}"],` +
      `"style":"bold" or "minimal" or "electric" (pick the best fit)}`,
      600
    );
    const parsed = JSON.parse(text.replace(/```json|```/g, '').trim());
    return {
      color: base.color, // color stays name-derived: deterministic identity
      style: ['bold','minimal','electric'].includes(parsed.style) ? parsed.style : base.style,
      tagline: String(parsed.tagline || base.tagline).slice(0, 80),
      bio_linkedin: String(parsed.bio_linkedin || base.bio_linkedin).slice(0, 240),
      bio_x: String(parsed.bio_x || base.bio_x).slice(0, 140),
      hooks: Array.isArray(parsed.hooks) && parsed.hooks.length >= 3
        ? parsed.hooks.slice(0, 5).map(h => String(h).slice(0, 160))
        : base.hooks,
    };
  } catch {
    return base; // never block signup on the AI call
  }
}

async function callClaude(prompt, maxTokens = 400) {
  const res = await fetch('https://api.anthropic.com/v1/messages', {
    method: 'POST',
    headers: {
      'content-type': 'application/json',
      'x-api-key': API_KEY,
      'anthropic-version': '2023-06-01',
    },
    body: JSON.stringify({
      model: MODEL,
      max_tokens: maxTokens,
      messages: [{ role: 'user', content: prompt }],
    }),
  });
  if (!res.ok) throw new Error(`anthropic_${res.status}`);
  const data = await res.json();
  return (data.content || []).filter(b => b.type === 'text').map(b => b.text).join('\n').trim();
}

export async function generateDraft({ name, niche, topic, style }) {
  if (!API_KEY) return TEMPLATES[style](name, topic);
  try {
    return await callClaude(
      `You write social posts for "${name}", whose niche is "${niche}".\n` +
      `Style guide: ${STYLE_GUIDES[style]}\n` +
      `Write ONE LinkedIn/X post about: ${topic}.\n` +
      `Under 120 words. Output only the post text — no preamble, no quotes.`
    );
  } catch {
    return TEMPLATES[style](name, topic); // graceful fallback
  }
}

export async function generateHooks({ name, topic }) {
  const fallback = [
    `Everyone is wrong about ${topic}. Here's what ${name.split(' ')[0]} sees instead:`,
    `I spent 3 years on ${topic} so you can learn it in 3 minutes.`,
    `The ${topic} advice nobody gives you (because it's unglamorous):`,
    `Stop scrolling if ${topic} is on your roadmap this year.`,
    `${cap(topic)}, explained the way I wish someone had explained it to me:`,
  ];
  if (!API_KEY) return fallback;
  try {
    const text = await callClaude(
      `Write exactly 5 scroll-stopping first lines (hooks) for social posts about "${topic}" ` +
      `by a creator named ${name}. One per line. No numbering, no quotes, nothing else.`,
      300
    );
    const lines = text.split('\n').map(l => l.trim()).filter(Boolean).slice(0, 5);
    return lines.length === 5 ? lines : fallback;
  } catch {
    return fallback;
  }
}

/** Rewrite a status update in the profile's on-brand style. Plus & Pro feature. */
export async function polishStatus({ name, niche, style, content }) {
  const first = name.split(' ')[0];
  const fallback = ({
    bold: `${content} — nobody remembers quiet builders. ${first} ships loud.`,
    minimal: `${content.toLowerCase().replace(/\.$/, '')} · quietly shipped.`,
    electric: `${content} ⚡ momentum compounds — another rep for ${first}.`,
  })[style] || content;
  if (!API_KEY) return fallback.slice(0, 280);
  try {
    const text = await callClaude(
      `Rewrite this status update in a ${style} personal-brand voice for ${name} (niche: ${niche}).\n` +
      `Keep it under 220 characters, first person, no hashtags, no quotes around it.\n` +
      `Status: ${content}\nOutput only the rewritten status.`,
      200
    );
    return (text || fallback).slice(0, 280);
  } catch {
    return fallback.slice(0, 280);
  }
}
